// Generated by CoffeeScript 1.7.1
var americano, fs, path, port, start;

americano = require('americano');

fs = require('fs');

path = require('path');

start = function(options, callback) {
  var config, configPath;
  if (options == null) {
    options = {};
  }
  options.name = 'Contacts';
  options.port = options.port;
  options.host = process.env.HOST || "0.0.0.0";
  options.root = options.root || __dirname;
  if (!fs.existsSync(configPath)) {
    config = {
      apps: {}
    };
    configPath = path.join(process.cwd(), 'config.json');
    fs.writeFileSync(configPath, JSON.stringify(config));
  }
  return americano.start(options, function(app, server) {
    return callback(null, app, server);
  });
};

if (!module.parent) {
  port = process.env.PORT || 9114;
  start({
    port: port
  }, function(err) {
    if (err) {
      console.log("Initialization failed, not starting");
      console.log(err.stack);
      return process.exit(1);
    }
  });
}

module.exports.start = start;
